config/routes.rb
Rails.application.routes.draw do

  root :to => 'pages#home'  
  resources :articles, :only => [:show, :index]
  resources :companies, :only => [:show, :index]
  resources :users, :only => [:create, :index, :home, :new]
  resources :portfolios, :only => [:show, :new, :create]
  
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  
end

app/models/company.rb
class Company < ApplicationRecord
    has_and_belongs_to_many :portfolios    
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    belongs_to :user, :optional => true
    has_and_belongs_to_many :companies
end

app/models/user.rb
class User < ApplicationRecord
    has_many :portfolios
    has_many :companies
    has_secure_password
    validates :email, :uniqueness => true, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :fetch_user

    def fetch_user
        @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
        session[:user_id] = nil unless @current_user.present? # logout non-current users.
    end

    def check_for_login
        redirect_to login_path unless @current_user.present?
    end
    
end


 

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @articles = Article.find params[:id]
  end

  private
  def articles_params
    params.require(:articles).permit(:title)
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def show
    @company = Company.find params[:id]
    StockQuote::Stock.new(:api_key => 'pk_16a849fd637243a79fff90fa4d42bc5d')
    info = StockQuote::Stock.quote @company.stock_code
    @price = info.latest_price
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
    end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
    before_action :check_for_login

    def new
        @portfolio = Portfolio.new
        @companies = Company.all
        
    end

    def info
        StockQuote::Stock.new(:api_key => 'pk_16a849fd637243a79fff90fa4d42bc5d')
        @symbol = params[symbol].upcase
        info = StockQuote::Stock.quote @symbol
        @price = info.latest_price
    end


    def create
        portfolio = Portfolio.create portfolio_params
        # portfolio.companies << companies
        @current_user.portfolios << portfolio #give the stock in a portfolio to the current user.
        redirect_to root_path
    end

    def show
        @portfolio = Portfolio.find params[:id]
    end
    
    def edit
        @portfolio = Portfolio.new
    end

    private
    def portfolio_params
        params.require(:portfolio).permit(:title, :company_ids => [])
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController


    def create  
        user = User.find_by :email => params[:email]
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path
        else
            flash[:error] = 'Sorry, login failed, Please login again.'
            redirect_to login_path
        end
    end

    def destroy
        session[:user_id] = 'delete'
        redirect_to login_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :check_for_user => [:index]

    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new user_params
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path
        else
            render :new
        end
    end 

    private
    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/articles/index.html.erb
<div class='ab'>
<h4>Different investment Philosophies at a Glance</h4>
</div>


<% @articles.each do |article| %>
<ul>
    <ul>About: <%= article.title %></ul>
    <ul>Investment philosophy: <%= article.about%></ul>
    <div class='image'>
    <ul><%= image_tag article.image %></ul>
    </div>
</ul>
<% end %>

app/views/articles/show.html.erb
<h1>Different Investment Philosophies</h1>

<div class=container>
    <p>
        <%= @articles.title %>
        <%= @articles.about %>
        <%# <img src="..." class="rounded float-left" alt="..."> %>
        <%= image_tag @articles.image %>
    </p>
</div>

app/views/companies/index.html.erb
<div class='c'>
<h4>Here's a list of Quality researched stocks</h4>
</div>

<% @companies.each do |company| %>
    <li>
        <%=link_to company.name, company %>
        <%= company.history %>
    </li>

<% end %>

app/views/companies/show.html.erb
<div class='ab'>
    <h4>Here's a concise yet researched paper on the stock in question</h4>
</div>
<div class="b">
<%= @company.name %>
<%= @company.history %>
<%= @company.current %>
<%= @company.future %>
<%= @company.potential %>

<%= @price %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stock Investments</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
      <nav class="container">
      <button type="button" class="btn btn-secondary">
        <%= link_to 'Home', root_path %>
        </button>
        
        <% if @current_user.present? %>
          <button type="button" class="btn btn-secondary">
          <%= link_to 'Investmens', portfolio_path(@current_user.portfolios.last) %>
          </button>
          <button type="button" class="btn btn-secondary">
          <%= link_to 'Knowledge centre', articles_path %>
          </button>
          <button type="button" class="btn btn-secondary">
          <%= link_to 'Researched Stocks', companies_path %>
          </button>
          <button type="button" class="btn btn-secondary">
          <%= link_to 'Logout', login_path, :method => 'delete' %>
          </button>
        <% else %>
          <button type="button" class="btn btn-secondary">
          <%= link_to 'Sign Up to Our Investment Insights', new_user_path %>
          </button>
          <button type="button" class="btn btn-secondary">
          <%= link_to 'Sign in', login_path %>
          </button>

        <% end %>
      </nav>
    </div>

    <div class= container>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class='bc'>
    <h3>Welcome to the world of Quality investments.</h3>
</div>  

<p>Welcome <%= @current_user.email if @current_user.present? %></p>

<p>
    <p><%= link_to 'Click to understand more about an company that you may want to invest in.', companies_path %></p>
    <a href="/articles">
        Click here to learn about intersting articles on invesments philosophy.
    </a>
    <%= link_to 'Create Portfolio', new_portfolio_path %>
</p>

app/views/portfolio/show.html.erb
 <h4> My Portfolio </h4>  

<% @portfolio.companies.each do |company| %>
    <h1><%= company.name %></h1>
    <h2><%= company.history %></h2>
    <%= company.potential %>
    <%= company.current %>
    <%= company.potential %>
<% end %>

app/views/portfolios/_form.html.erb
<div class='aa'>
    <%= form_for @portfolio do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title %>
        <%= f.label :portfolio_amout %>
        $<%= f.number_field :portfolio_amount %>
        <%= f.label :stock_code %>
        <div class="stocks">
            <%= f.collection_check_boxes :company_ids, Company.all, :id, :stock_code %>
        </div>
        <%= f.submit 'Create', :class => 'buttonRight' %>

    <% end %>
</div>

<%# partial form and render it to the edit and new files within views. %>

app/views/portfolios/edit.html.erb
<h5>Your portfolio</h5>

<%= @current_user if current_user.present? %>


<%= render :partial => 'form' %>
   

    

app/views/portfolios/new.html.erb
<%= render :partial => 'form' %>

app/views/portfolios/show.html.erb
<br>
<br>
<h4> My Portfolio </h4>  

<% @portfolio.companies.each do |company| %>
    <div class="a">
    <%= link_to company.name, company %>
    <%= company.history %>
    <%= company.potential %>
    <%= company.current %>
    <%= company.potential %>
    </div>
<% end %>

app/views/session/new.html.erb
<h1>Log in</h1>

<% if flash[:error].present? %>
    <h2><% flash[:error] %></h2>
<% end %>

<%= form_tag login_path do %>
    <%= label_tag :email %>
    <%= email_field_tag :email %>
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    <%= submit_tag "Sign In" %>
<% end %>

app/views/stocks/index.html.erb
<% @stocks.each do |stocks| %>
        <ul>
            <li>Name: <%= stocks.name %></li>
            <li>History: <%= stocks.history %></li>
            <li>Currently whats happening: <%= stocks.current%></li>
            <li>Potential: <%= stocks.potential %></li>
        </ul>
<% end %>

app/views/stocks/new.html.erb
<h1>Stock Information<h1>

<p>Here's your stock information <%= @current_user if @current_user.present? ></p>

<%= @articles.name %>
<%= @articles.history %>
<%= @articles.current %>
<%= @articles.future %>
<%= @articles.potential %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
    <ol>
        <% @user.errors.full_messages.each do |msg| %>
            <li> <%= msg %></li>
        <% end %>
    </ol>
<% end %>
        

<%= form_for @user do |f| %>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation%>
    <%= f.submit %>
<% end %>